volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: arktorion/foodgram-backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: arktorion/foodgram-frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db
      - backend
  gateway:
    image: arktorion/foodgram-gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - 8001:80
    depends_on:
      - db
      - backend
      - frontend
